### ISSUE TITLE
Is it OK to make this repo add support files not found in Norbert Preining’s Git mirror?

### ISSUE THREAD

**Issue by doronbehar** [tectonic-typesetting/tectonic-texlive-bundles#1]
So there is this latex package called [culmus-latex](http://www.guyrutenberg.com/culmus-latex/) which isn't distributed in the default Git mirror of all texlive packages. I'd like it to be available to everyone who wants to `\usepackage{culmus}`. Naturally, contributing this would require manually downloading files from https://sourceforge.net/p/ivritex/culmus-latex/ci/master/tree/ and putting them in the bundle.

**Comment by pkgw** [comment]
Apologies for taking a while to reply to you. Yes, this is definitely fine, and in fact I do this manually for a few packages of personal interest. I have start improving my tooling for creating bundles, and as of now the way to do this is to add files to the `bundles/tlextras/extras/` directory.

While I'm working on this I'll open a PR to add this package.

**Comment by pkgw** [comment]
Hmm, actually. I see that the released package file (`culmus-latex-0.7-r1.tar.gz`) includes a lot of font files. This is fine, but I'd rather not be adding a bunch of large-ish data files to the source repo. Are these files required for the package? If so, I'll wire up some infrastructure to fetch and unpack the source tarball as part of the workflow.

**Comment by doronbehar** [comment]
> I see that the released package file (`culmus-latex-0.7-r1.tar.gz`) includes a lot of font files.

Interesting.. Because I got the impression that distributions are supposed to put the fonts themselves in a separate package. The fonts themselves are supposed to be sourced from [here](http://culmus.sourceforge.net/) and for instance, there's an aur package only for [culmus fonts](https://aur.archlinux.org/packages/culmus/). 

I think it will make sense for this project to not include the fonts, considering that every distribution manages fonts of the system in a potentially different way. Though it will need some testings.

> Yes, this is definitely fine, and in fact I do this manually for a few packages of personal interest. I have start improving my tooling for creating bundles, and as of now the way to do this is to add files to the `bundles/tlextras/extras/` directory.

Sounds great! Thanks for doing this professor :).

**Comment by pkgw** [comment]
Ah, and as another follow-up .. it appears that the 0.7 version of the `culmus` package is designed for the `inputenc` / `fontenc` system, which is not compatible with Tectonic, which instead is based on XeTeX and requires Unicode input files with the `fontspec` system. Here's a related StackExchange question:

https://tex.stackexchange.com/questions/423118/xetex-doesnt-find-a-font

Is there an aspect of Culmus that we can confirm *should* be used with XeTeX? Is there a newer version somewhere? The 0.7 version is from way back in 2008.

**Comment by doronbehar** [comment]
Technically I don't know if culmus provides some functionality I lack with my current documents. I haven't tested it yet with any tex system. There are some issues I always experience with very minimal documents, related to Hebrew, and I was only wondering whether culmus will be able to solve them. I guess you are right though, it doesn't fit this project, and no, I guess there is no newer version.

What I do feel missing for general Hebrew support, are hyphenation patterns (https://github.com/tectonic-typesetting/tectonic/issues/553), and with the font "David CLM", I get these `\item`s:

![ZENIX-selection-2020-10-11T20:46:43+03:00](https://user-images.githubusercontent.com/10998835/95685813-c4aeaf00-0be9-11eb-945f-55b1fbdeac1c.png)

And warnings:

```
warning: letter.tex:43: Overfull \hbox (0.10017pt too wide) in paragraph at lines 40--43
warning: letter.tex:83: Missing character: There is no ��� in font David CLM Medium/OT:script=hebr;language=DFLT;!
warning: could not represent character "•" (0x2022) in font "David CLM Medium/OT:script=hebr;language=DFLT;"
warning:   you may need to load the `fontspec` package and use (e.g.) \setmainfont to
warning:   choose a different font that covers the unrepresentable character(s)
```

My hope was that culmus will magically solve these, but I'm rather satisfied with my current workaround:

```tex
\newfontfamily\bulletfont{Liberation Serif}

\begin{itemize}
	{\bulletfont \item \ } ...
	{\bulletfont \item \ } ...
	{\bulletfont \item \ } ...
\end{itemize}
```

Thanks again for your assistance, and for maintaining this well designed project.

**Comment by doronbehar** [comment]
Oh and I do use `fontspec`, this way:

```tex
\setmainfont{David CLM}
\setsansfont{Liberation Sans}
\setmonofont{Liberation Mono}
\newfontfamily\hebrewfont{David CLM}[Script=Hebrew]
\newfontfamily\hebrewfontsf{Liberation Serif}[Script=Hebrew]
\newfontfamily\hebrewfonttt{Liberation Mono}[Script=Hebrew]
```

Adding `\usepackage{fontspec}` doesn't make a difference.

**Comment by doronbehar** [comment]
This is no call for help or a bug, I'm just reporting an experience I have a workaround for so I don't complain :).

**Comment by pkgw** [comment]
Thanks for the detailed information! From my read of the code in the `culmus` package, it is pretty much entirely oriented around setting up Hebrew fonts in the old-style system, so I don't think it would help with the other issues you describe.

Issues like tectonic-typesetting/tectonic#553 are ones that I am trying to address with the TexLive 2020 update. I'll see what I can address there.

It's not obvious to me how to deal with your `\item` issue. If you discover a package that helps address it, please open a new issue with the information! It sounds as if it might be just an issue in XeTeX+TeXLive in general, and I don't really want to go too far down the road of patching out issues that aren't specific to Tectonic ... but if we can solve a genuine problem for you, we should.

I'm going to close this issue since my conclusion is that it doesn't make sense to try to add `culmus` to the default bundle, but if there are any other Tectonic-specific issues that we could change to improve Hebrew support, please open new issues as needed.
