### ISSUE TITLE
Update to TeX Live 2020

### ISSUE THREAD

**Issue by XVilka** [tectonic-typesetting/tectonic-texlive-bundles#2]
It was released quite some time ago.

**Comment by pkgw** [comment]
Progress is being made! I have now moved the bundle-creation setup to this new repo with a substantially cleaner infrastructure. I have a draft TL2020 bundle and it is passing [some basic tests](https://github.com/tectonic-typesetting/tectonic-texlive-bundles/tree/master/tests). I'm currently going through the issue backlogs and seeing which ones I can address before I upload a beta.
